baseURL: https://selenium-compose.io
title: Selenium Compose

params:
  baseURL: https://selenium-compose.io
  description: Description-driven selenium tests composition
  github_repo: https://github.com/selenium-compose/selenium-compose/issues/new
  slack: https://join.slack.com/t/seleniumcompose/shared_invite/enQtMzYwMzI2MTQ2Njc4LTQ2MDFmMjBhYTllNDdhNjc5NDM3ZGUzNmZiMDZkOGM1NDcxMTdjYWM4OWMxMmRiYThlZWQ1NTVkOGE0NDVkMWY
  gitter: https://gitter.im/SelenumC/Lobby
  ghrepo: https://github.com/selenium-compose/selenium-compose.io/

menu:
  global:
  - name: Getting Started
    identifier: getting-started
    url: /getting-started/quick-start/
    weight: 1
  - name: Docs
    identifier: docs
    url: /scenario/overview/
    weight: 2
  - name: Community
    url: /community
    identifier: community
    weight: 3
  - name: Contribute
    url: /contribute
    identifier: contribute
    weight: 4

  docs:
  - name: Getting Started
    identifier: getting-started
    url: /getting-started/quick-start/
    weight: 2
  - name: Scenario
    identifier: scenario
    url: /scenario
    weight: 25
  - name: Steps
    identifier: steps
    url: /steps
    weight: 30
  - name: Expectations
    identifier: expectations
    url: /expectations
    weight: 35
